-- Phase 1: Seed users
-- IMMUTABLE -- do not modify after first apply. Create Vn migration for corrections.
-- Passwords: admin123 (ADMIN), operator123 (OPERATOR)
-- Hashes generated with BCrypt cost 12 -- compatible with Spring BCryptPasswordEncoder
--
-- NOTE: $2b$ prefix is equivalent to $2a$ per the BCrypt spec and is accepted by
-- Spring Security's BCryptPasswordEncoder (backed by jBCrypt). If integration tests
-- return 401 despite correct credentials, create V3__fix_seed_hashes.sql with UPDATE
-- statements using $2a$-prefixed hashes from Spring's own BCryptPasswordEncoder.
-- Do NOT edit this file -- Flyway checksum validation treats edits as tampering.

INSERT INTO users (email, password, role, full_name) VALUES
    ('admin@example.com',
     '$2b$12$9W.v3G.478iDq0Cxd4SybeBPGjo1sGkfX9kDWU8UjDkFD7UHINuOK',
     'ADMIN',
     'Admin User'),
    ('operator@example.com',
     '$2b$12$AvJo41wIAJB6Tz01UFbSiue9qPqBjhvA6V2ojFAS9Kx5qZAJpvifC',
     'OPERATOR',
     'Operator User');
